
import { Movie } from './types';

export const MOVIES: Movie[] = [
  {
    id: 'anikalupo',
    title: 'Aníkúlápó',
    poster: 'https://picsum.photos/seed/anikalupo/300/400',
    downloadLink: '#',
    genre: 'Fantasy',
    category: 'Epic',
    releaseDate: '2022-09-30',
    stars: ['Kunle Remi', 'Bimbo Ademoye', 'Sola Sobowale'],
    runtime: '2h 22m',
    rating: 8.9,
    description: 'A mystical bird bestows upon a traveler the power to raise the dead, leading to both fame and unforeseen consequences.',
    popularity: 95,
    createdAt: '2022-09-01T10:00:00Z',
    updatedAt: '2022-09-30T12:00:00Z',
    trailerId: 'dkl_a2W50_A',
    comments: [
        { id: 'c1', parentId: null, reviewer: 'CinemaFan22', rating: 5, comment: 'Absolutely breathtaking! The visuals and storytelling are top-notch. A must-watch Yoruba epic.', date: '2022-10-05', replies: [] },
        { id: 'c2', parentId: null, reviewer: 'Adebayo P.', rating: 4, comment: 'A great story about power and consequence. Kunle Remi was fantastic.', date: '2022-10-02', replies: [] },
    ],
  },
  {
    id: 'king-of-thieves',
    title: 'King of Thieves (Ogundabede)',
    poster: 'https://picsum.photos/seed/kingofthieves/300/400',
    downloadLink: '#',
    genre: 'Action',
    category: 'Epic',
    releaseDate: '2022-04-08',
    stars: ['Femi Adebayo', 'Toyin Abraham', 'Odunlade Adekola'],
    runtime: '2h 10m',
    rating: 8.5,
    description: 'A powerful bandit terrorizes a kingdom, and only a formidable hunter with a mysterious past can stop him.',
    popularity: 92,
    createdAt: '2022-03-15T10:00:00Z',
    updatedAt: '2022-04-08T12:00:00Z',
    trailerId: 'i_F4vj0yL7o',
    comments: [],
  },
  {
    id: 'jagun-jagun',
    title: 'Jagun Jagun (The Warrior)',
    poster: 'https://picsum.photos/seed/jagunjagun/300/400',
    downloadLink: '#',
    genre: 'War',
    category: 'Action',
    releaseDate: '2023-08-10',
    stars: ['Femi Adebayo', 'Lateef Adedimeji', 'Bimbo Ademoye'],
    runtime: '2h 14m',
    rating: 9.1,
    description: 'A young man determined to become a mighty warrior joins an elite army, only to find himself in a ruthless battle for power.',
    popularity: 98,
    createdAt: '2023-07-20T10:00:00Z',
    updatedAt: '2023-08-10T12:00:00Z',
    trailerId: 'g340A9_2n-c',
    comments: [
        { 
          id: 'ai-jagun', 
          parentId: null, 
          reviewer: 'Cinemax AI', 
          isAI: true, 
          comment: 'Analysis: "Jagun Jagun" excels in its depiction of ambition and betrayal, set against a backdrop of intense, well-choreographed action sequences. The character arc of the protagonist serves as a powerful narrative anchor. Recommended for viewers who appreciate epic storytelling and complex character dynamics.', 
          date: '2023-08-16', 
          replies: [] 
        },
        { id: 'j1', parentId: null, reviewer: 'NollywoodLover', rating: 5, comment: 'The best action movie to come out of Nigeria in years. The fight scenes are incredible!', date: '2023-08-12', replies: [
             { id: 'j1-1', parentId: 'j1', reviewer: 'Tunde', comment: 'I completely agree! I was on the edge of my seat the whole time.', date: '2023-08-13', replies: [] }
        ] },
        { id: 'j2', parentId: null, reviewer: 'Tunde', rating: 5, comment: 'Femi Adebayo is a genius. This movie is an instant classic.', date: '2023-08-11', replies: [] },
        { id: 'j3', parentId: null, reviewer: 'Sarah G.', rating: 4, comment: 'Great plot and character development. A little long, but worth it.', date: '2023-08-15', replies: [] },
    ],
  },
  {
    id: 'ile-owo',
    title: 'Ilé Owo (House of Money)',
    poster: 'https://picsum.photos/seed/ileowo/300/400',
    downloadLink: '#',
    genre: 'Horror',
    category: 'Thriller',
    releaseDate: '2022-06-24',
    stars: ['Bukunmi Oluwasina', 'Tina Mba', 'Efa Iwara'],
    runtime: '1h 55m',
    rating: 7.8,
    description: 'A young woman from a poor background finds love with a wealthy man, but his family harbors a dark and terrifying secret.',
    popularity: 80,
    createdAt: '2022-06-01T10:00:00Z',
    updatedAt: '2022-06-24T12:00:00Z',
  },
  {
    id: 'omo-ghetto',
    title: 'Omo Ghetto: The Saga',
    poster: 'https://picsum.photos/seed/omoghetto/300/400',
    downloadLink: '#',
    genre: 'Comedy',
    category: 'Action',
    releaseDate: '2020-12-25',
    stars: ['Funke Akindele', 'Chioma Akpotha', 'Eniola Badmus'],
    runtime: '2h 25m',
    rating: 8.2,
    description: 'A tale of twin sisters leading separate lives, one a ghetto-raised gangster and the other a wealthy, uptight lady, whose worlds collide.',
    popularity: 88,
    createdAt: '2020-12-01T10:00:00Z',
    updatedAt: '2020-12-25T12:00:00Z',
    trailerId: 'kS-J6aGvRcs',
  },
  {
    id: 'sugar-rush',
    title: 'Sugar Rush',
    poster: 'https://picsum.photos/seed/sugarrush/300/400',
    downloadLink: '#',
    genre: 'Action',
    category: 'Comedy',
    releaseDate: '2019-12-25',
    stars: ['Adesua Etomi-Wellington', 'Bimbo Ademoye', 'Bisola Aiyeola'],
    runtime: '2h 0m',
    rating: 7.5,
    description: 'Three sisters discover a huge sum of money and must go on the run from dangerous criminals and the authorities.',
    popularity: 85,
    createdAt: '2019-12-01T10:00:00Z',
    updatedAt: '2019-12-25T12:00:00Z',
  },
  {
    id: 'ayanmo',
    title: 'Ayinla',
    poster: 'https://picsum.photos/seed/ayinla/300/400',
    downloadLink: '#',
    genre: 'Musical',
    category: 'Drama',
    releaseDate: '2021-06-18',
    stars: ['Lateef Adedimeji', 'Omowunmi Dada', 'Bimbo Manuel'],
    runtime: '1h 50m',
    rating: 8.6,
    description: 'A biopic on the life of Ayinla Omowura, a popular Apala musician, exploring his rise to fame, his music, and his tragic death.',
    popularity: 89,
    createdAt: '2021-06-01T10:00:00Z',
    updatedAt: '2021-06-18T12:00:00Z',
  },
  {
    id: 'mokalik',
    title: 'Mokalik (Mechanic)',
    poster: 'https://picsum.photos/seed/mokalik/300/400',
    downloadLink: '#',
    genre: 'Coming-of-age',
    category: 'Drama',
    releaseDate: '2019-05-31',
    stars: ['Tooni Afolayan', 'Femi Adebayo', 'Simi'],
    runtime: '1h 40m',
    rating: 7.2,
    description: 'An 11-year-old boy from the suburbs spends a day as an apprentice at a mechanic workshop to understand life from a different perspective.',
    popularity: 75,
    createdAt: '2019-05-01T10:00:00Z',
    updatedAt: '2019-05-31T12:00:00Z',
  },
   {
    id: 'breaded-life',
    title: 'Breaded Life',
    poster: 'https://picsum.photos/seed/breadedlife/300/400',
    downloadLink: '#',
    genre: 'Dramedy',
    category: 'Drama',
    releaseDate: '2021-04-16',
    stars: ['Timini Egbuson', 'Bimbo Ademoye', 'Tina Mba'],
    runtime: '2h 9m',
    rating: 8.0,
    description: 'A spoiled rich kid wakes up one day to find that no one in his family recognizes him, forcing him to learn how to survive on the streets.',
    popularity: 83,
    createdAt: '2021-04-01T10:00:00Z',
    updatedAt: '2021-04-16T12:00:00Z',
  },
  {
    id: 'the-wedding-party',
    title: 'The Wedding Party',
    poster: 'https://picsum.photos/seed/weddingparty/300/400',
    downloadLink: '#',
    genre: 'Rom-Com',
    category: 'Romance',
    releaseDate: '2016-12-16',
    stars: ['Adesua Etomi-Wellington', 'Banky Wellington', 'Sola Sobowale'],
    runtime: '1h 40m',
    rating: 7.9,
    description: 'The lavish wedding of a Yoruba bride and an Igbo groom turns into a chaotic and hilarious series of events as their families clash.',
    popularity: 90,
    createdAt: '2016-12-01T10:00:00Z',
    updatedAt: '2016-12-16T12:00:00Z',
  },
  {
    id: 'gold-statue',
    title: 'Gold Statue',
    poster: 'https://picsum.photos/seed/goldstatue/300/400',
    downloadLink: '#',
    genre: 'Adventure',
    category: 'Comedy',
    releaseDate: '2019-05-17',
    stars: ['Gabriel Afolayan', 'Kunle Remi', 'Richard Mofe-Damijo'],
    runtime: '2h 25m',
    rating: 7.1,
    description: 'Two young men go on a perilous adventure in search of a mythical gold statue, a journey that tests their wits and friendship.',
    popularity: 77,
    createdAt: '2019-05-01T10:00:00Z',
    updatedAt: '2019-05-17T12:00:00Z',
  },
  {
    id: 'elevator-baby',
    title: 'Elevator Baby',
    poster: 'https://picsum.photos/seed/elevatorbaby/300/400',
    downloadLink: '#',
    genre: 'Drama',
    category: 'Thriller',
    releaseDate: '2019-10-11',
    stars: ['Toyin Abraham', 'Timini Egbuson'],
    runtime: '1h 24m',
    rating: 7.8,
    description: 'A privileged young man and a struggling pregnant woman are trapped in an elevator, forcing them to rely on each other as she goes into labor.',
    popularity: 81,
    createdAt: '2019-10-01T10:00:00Z',
    updatedAt: '2019-10-11T12:00:00Z',
  },
  {
    id: 'citation',
    title: 'Citation',
    poster: 'https://picsum.photos/seed/citation/300/400',
    downloadLink: '#',
    genre: 'Drama',
    category: 'Drama',
    releaseDate: '2020-11-06',
    stars: ['Temi Otedola', 'Jimmy Jean-Louis', 'Joke Silva'],
    runtime: '2h 31m',
    rating: 7.6,
    description: 'A bright student takes on the academic establishment when she reports a popular professor who tried to sexually assault her.',
    popularity: 84,
    createdAt: '2020-10-15T10:00:00Z',
    updatedAt: '2020-11-06T12:00:00Z',
  },
  {
    id: 'gangs-of-lagos',
    title: 'Gangs of Lagos',
    poster: 'https://picsum.photos/seed/gangsoflagos/300/400',
    downloadLink: '#',
    genre: 'Crime',
    category: 'Action',
    releaseDate: '2023-04-07',
    stars: ['Tobi Bakre', 'Adesua Etomi-Wellington', 'Chike Osebuka'],
    runtime: '2h 4m',
    rating: 8.3,
    description: 'A group of friends navigate the dangerous and politically charged streets of Isale Eko, Lagos, rising through the criminal underworld.',
    popularity: 93,
    createdAt: '2023-03-15T10:00:00Z',
    updatedAt: '2023-04-07T12:00:00Z',
  },
  {
    id: 'ijogbon',
    title: 'Ijogbon',
    poster: 'https://picsum.photos/seed/ijogbon/300/400',
    downloadLink: '#',
    genre: 'Coming-of-age',
    category: 'Thriller',
    releaseDate: '2023-10-13',
    stars: ['Bolanle Ninalowo', 'Ruby Akubueze', 'Kayode Ojuolape'],
    runtime: '1h 45m',
    description: 'Four teenagers from a rural village in South-West Nigeria stumble upon a pouch of uncut diamonds and must decide what to do with them.',
    rating: 7.9,
    popularity: 87,
    createdAt: '2023-10-01T10:00:00Z',
    updatedAt: '2023-10-13T12:00:00Z',
  }
];

export const STATIC_PAGES = {
  privacy: {
    title: "Privacy Policy",
    content: "Our commitment to your privacy is paramount. This policy outlines how we collect, use, and protect your personal information. We do not share your data with third parties without your explicit consent. All data is stored securely and handled with the utmost care."
  },
  dmca: {
    title: "DMCA Takedown Policy",
    content: "Yoruba Cinemax respects intellectual property rights. If you believe your copyrighted work has been infringed upon, please submit a DMCA takedown notice to our legal team with the required documentation. We will promptly investigate and take appropriate action."
  },
  contact: {
    title: "Contact Us",
    content: "Have a question or feedback? We'd love to hear from you. Reach out to our support team at support@yorubacinemax.com or call us at +234-123-456-7890. Our office is located at 123 Film House, Ikeja, Lagos."
  },
  advertise: {
    title: "Advertise With Us",
    content: "Reach a dedicated audience of Yoruba movie lovers. We offer a range of advertising solutions, from banner ads to sponsored content. Contact our advertising department at ads@yorubacinemax.com to discuss partnership opportunities."
  }
};